[tool.poetry]
name = "invoice-handler"
version = "0.1.0"
description = ""
authors = ["Aleksandr Zubkov <yalishenda.z@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
